/**
 * Secure client-side ID utilities.
 *
 * Centralizes ID generation to ensure we always use cryptographically
 * secure random values (Web Crypto API) instead of predictable alternatives
 * like Math.random() or Date.now().
 *
 * The primary keys in the database are UUIDs generated by PostgreSQL's
 * gen_random_uuid() (equivalent to uuid_generate_v4()). This module provides
 * the matching client-side equivalent for optimistic updates and temporary IDs.
 */

/**
 * Generates a cryptographically secure UUID v4.
 * Uses the Web Crypto API (crypto.randomUUID), which is available in all
 * modern browsers and in Node.js 14.17+.
 *
 * Falls back to a polyfill for environments that don't support it (rare).
 */
export function generateId(): string {
  if (
    typeof crypto !== 'undefined' &&
    typeof crypto.randomUUID === 'function'
  ) {
    return crypto.randomUUID();
  }

  // Polyfill for environments without crypto.randomUUID
  // Using crypto.getRandomValues for secure bytes
  if (typeof crypto !== 'undefined' && typeof crypto.getRandomValues === 'function') {
    const bytes = new Uint8Array(16);
    crypto.getRandomValues(bytes);
    // Set version (4) and variant bits per RFC 4122
    bytes[6] = (bytes[6] & 0x0f) | 0x40;
    bytes[8] = (bytes[8] & 0x3f) | 0x80;
    const hex = Array.from(bytes).map(b => b.toString(16).padStart(2, '0')).join('');
    return `${hex.slice(0, 8)}-${hex.slice(8, 12)}-${hex.slice(12, 16)}-${hex.slice(16, 20)}-${hex.slice(20)}`;
  }

  // Last resort: throw — do NOT fall back to Math.random() for IDs
  throw new Error('crypto API not available — cannot generate a secure ID');
}

/** UUID v4 regex pattern for validation */
export const UUID_PATTERN =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/** Returns true if the string is a valid UUID v4 */
export function isUUID(value: string): boolean {
  return UUID_PATTERN.test(value);
}

/** Returns true if the string is a valid numeric ticket_number (human reference) */
export function isTicketNumber(value: string): boolean {
  return /^\d+$/.test(value);
}
