project_id = "kcxwealimsfxqstoprdg"

[functions.check-rate-limit]
verify_jwt = true

[functions.create-new-user]
verify_jwt = false

[functions.delete-user-admin]
verify_jwt = false

[functions.admin-update-user]
verify_jwt = false

[functions.invite-user-resend]
verify_jwt = false

[functions.reset-password-with-token]
verify_jwt = false
