-- Advisor do Supabase (multiple_permissive_policies), última parte (as
-- tabelas fora do fluxo de chamados; profiles fica em migração própria).
--
-- Nestas tabelas as policies antigas eram "ALL" (uma por perfil gestor) mais
-- uma de SELECT mais larga. Uma policy ALL também vale para SELECT, daí a
-- sobreposição. Agora cada tabela tem uma policy por operação:
--   gestor  = OR de todas as antigas ALL (USING e WITH CHECK eram iguais);
--   SELECT  = gestor OR a antiga policy de leitura;
--   INSERT, UPDATE, DELETE = gestor.
-- O acesso resultante é o mesmo de antes (conferido com os 4 perfis de teste).
--
-- O DO de cada tabela apaga as policies existentes dela; a lista foi
-- conferida em 23/09/2026 e são só as que este arquivo recria.

-- audit_log: só leitura
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='audit_log' AND cmd='SELECT' LOOP EXECUTE format('DROP POLICY %I ON public.audit_log', p); END LOOP; END $$;
CREATE POLICY audit_log_select ON public.audit_log FOR SELECT TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND changed_by IN (SELECT profiles.id FROM public.profiles WHERE profiles.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))))));

-- contracts
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='contracts' LOOP EXECUTE format('DROP POLICY %I ON public.contracts', p); END LOOP; END $$;
CREATE POLICY contracts_select ON public.contracts FOR SELECT TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid()))))) OR ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR (company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))))));
CREATE POLICY contracts_insert ON public.contracts FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))));
CREATE POLICY contracts_update ON public.contracts FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid()))))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))));
CREATE POLICY contracts_delete ON public.contracts FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))));

-- custom_field_values
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='custom_field_values' LOOP EXECUTE format('DROP POLICY %I ON public.custom_field_values', p); END LOOP; END $$;
CREATE POLICY custom_field_values_select ON public.custom_field_values FOR SELECT TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR EXISTS (SELECT 1 FROM public.custom_fields cf WHERE cf.id = custom_field_values.custom_field_id AND cf.company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY custom_field_values_insert ON public.custom_field_values FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR EXISTS (SELECT 1 FROM public.custom_fields cf WHERE cf.id = custom_field_values.custom_field_id AND cf.company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY custom_field_values_update ON public.custom_field_values FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR EXISTS (SELECT 1 FROM public.custom_fields cf WHERE cf.id = custom_field_values.custom_field_id AND cf.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR EXISTS (SELECT 1 FROM public.custom_fields cf WHERE cf.id = custom_field_values.custom_field_id AND cf.company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY custom_field_values_delete ON public.custom_field_values FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR EXISTS (SELECT 1 FROM public.custom_fields cf WHERE cf.id = custom_field_values.custom_field_id AND cf.company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));

-- custom_fields
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='custom_fields' LOOP EXECUTE format('DROP POLICY %I ON public.custom_fields', p); END LOOP; END $$;
CREATE POLICY custom_fields_select ON public.custom_fields FOR SELECT TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))))) OR (company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY custom_fields_insert ON public.custom_fields FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY custom_fields_update ON public.custom_fields FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY custom_fields_delete ON public.custom_fields FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));

-- services
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='services' LOOP EXECUTE format('DROP POLICY %I ON public.services', p); END LOOP; END $$;
CREATE POLICY services_select ON public.services FOR SELECT TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))))) OR (company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY services_insert ON public.services FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY services_update ON public.services FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY services_delete ON public.services FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))));

-- sla_configs
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='sla_configs' LOOP EXECUTE format('DROP POLICY %I ON public.sla_configs', p); END LOOP; END $$;
CREATE POLICY sla_configs_select ON public.sla_configs FOR SELECT TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid()))))) OR (company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) OR (SELECT public.is_equipe_interna((SELECT auth.uid())))));
CREATE POLICY sla_configs_insert ON public.sla_configs FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))));
CREATE POLICY sla_configs_update ON public.sla_configs FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid()))))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))));
CREATE POLICY sla_configs_delete ON public.sla_configs FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))));

-- ticket_kb_links
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='ticket_kb_links' LOOP EXECUTE format('DROP POLICY %I ON public.ticket_kb_links', p); END LOOP; END $$;
CREATE POLICY ticket_kb_links_select ON public.ticket_kb_links FOR SELECT TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (((SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))) AND public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid()))))) OR (EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_kb_links.ticket_id AND t.user_id = (SELECT auth.uid()))));
CREATE POLICY ticket_kb_links_insert ON public.ticket_kb_links FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (((SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))) AND public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY ticket_kb_links_update ON public.ticket_kb_links FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (((SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))) AND public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid()))))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (((SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))) AND public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid())))));
CREATE POLICY ticket_kb_links_delete ON public.ticket_kb_links FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (((SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role))) AND public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid())))));

-- time_entries
DO $$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='time_entries' LOOP EXECUTE format('DROP POLICY %I ON public.time_entries', p); END LOOP; END $$;
CREATE POLICY time_entries_select ON public.time_entries FOR SELECT TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (user_id = (SELECT auth.uid()) AND ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid())))))) OR ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR (public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))))));
CREATE POLICY time_entries_insert ON public.time_entries FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (user_id = (SELECT auth.uid()) AND ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid()))))));
CREATE POLICY time_entries_update ON public.time_entries FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (user_id = (SELECT auth.uid()) AND ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid())))))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (user_id = (SELECT auth.uid()) AND ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid()))))));
CREATE POLICY time_entries_delete ON public.time_entries FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND (SELECT public.is_master_company_user((SELECT auth.uid())))) OR (user_id = (SELECT auth.uid()) AND ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR public.get_ticket_company_id(ticket_id) = (SELECT public.get_user_company_id((SELECT auth.uid()))))));

