-- Advisor do Supabase (multiple_permissive_policies), sobra: tabelas em que
-- uma policy ALL (que também vale para SELECT) somava com uma de SELECT.
-- Mesmo método de 20260924070000: SELECT = OR das antigas; INSERT, UPDATE e
-- DELETE = a antiga ALL (em canned_responses, o OR dela com a de cada
-- operação). O acesso não muda.

-- assets
DO $q$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='assets' LOOP EXECUTE format('DROP POLICY %I ON public.assets', p); END LOOP; END $q$;
CREATE POLICY assets_select ON public.assets FOR SELECT TO authenticated USING (((company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))) OR (company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))));
CREATE POLICY assets_insert ON public.assets FOR INSERT TO authenticated WITH CHECK ((company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));
CREATE POLICY assets_update ON public.assets FOR UPDATE TO authenticated USING ((company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))) WITH CHECK ((company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));
CREATE POLICY assets_delete ON public.assets FOR DELETE TO authenticated USING ((company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));

-- canned_responses
DO $q$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='canned_responses' LOOP EXECUTE format('DROP POLICY %I ON public.canned_responses', p); END LOOP; END $q$;
CREATE POLICY canned_responses_select ON public.canned_responses FOR SELECT TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));
CREATE POLICY canned_responses_insert ON public.canned_responses FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR public.pode_gerir_automacao(company_id));
CREATE POLICY canned_responses_update ON public.canned_responses FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR public.pode_gerir_automacao(company_id)) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR public.pode_gerir_automacao(company_id));
CREATE POLICY canned_responses_delete ON public.canned_responses FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)) OR public.pode_gerir_automacao(company_id));

-- knowledge_base_articles
DO $q$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='knowledge_base_articles' LOOP EXECUTE format('DROP POLICY %I ON public.knowledge_base_articles', p); END LOOP; END $q$;
CREATE POLICY knowledge_base_articles_select ON public.knowledge_base_articles FOR SELECT TO authenticated USING ((SELECT public.is_equipe_interna((SELECT auth.uid()))) OR (NOT (SELECT public.is_equipe_interna((SELECT auth.uid()))) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND is_public = true AND status = 'published'::text));
CREATE POLICY knowledge_base_articles_insert ON public.knowledge_base_articles FOR INSERT TO authenticated WITH CHECK ((SELECT public.is_equipe_interna((SELECT auth.uid()))));
CREATE POLICY knowledge_base_articles_update ON public.knowledge_base_articles FOR UPDATE TO authenticated USING ((SELECT public.is_equipe_interna((SELECT auth.uid())))) WITH CHECK ((SELECT public.is_equipe_interna((SELECT auth.uid()))));
CREATE POLICY knowledge_base_articles_delete ON public.knowledge_base_articles FOR DELETE TO authenticated USING ((SELECT public.is_equipe_interna((SELECT auth.uid()))));

-- plans
DO $q$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='plans' LOOP EXECUTE format('DROP POLICY %I ON public.plans', p); END LOOP; END $q$;
CREATE POLICY plans_select ON public.plans FOR SELECT TO authenticated USING (true);
CREATE POLICY plans_insert ON public.plans FOR INSERT TO authenticated WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));
CREATE POLICY plans_update ON public.plans FOR UPDATE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))) WITH CHECK ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));
CREATE POLICY plans_delete ON public.plans FOR DELETE TO authenticated USING ((SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));

-- resolution_checklists
DO $q$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='resolution_checklists' LOOP EXECUTE format('DROP POLICY %I ON public.resolution_checklists', p); END LOOP; END $q$;
CREATE POLICY resolution_checklists_select ON public.resolution_checklists FOR SELECT TO authenticated USING ((((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))) OR (company_id IN (SELECT profiles.company_id FROM public.profiles WHERE profiles.id = (SELECT auth.uid()))));
CREATE POLICY resolution_checklists_insert ON public.resolution_checklists FOR INSERT TO authenticated WITH CHECK (((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));
CREATE POLICY resolution_checklists_update ON public.resolution_checklists FOR UPDATE TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))) WITH CHECK (((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));
CREATE POLICY resolution_checklists_delete ON public.resolution_checklists FOR DELETE TO authenticated USING (((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) AND company_id = (SELECT public.get_user_company_id((SELECT auth.uid())))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)));

-- ticket_assets
DO $q$ DECLARE p text; BEGIN FOR p IN SELECT policyname FROM pg_policies WHERE schemaname='public' AND tablename='ticket_assets' LOOP EXECUTE format('DROP POLICY %I ON public.ticket_assets', p); END LOOP; END $q$;
CREATE POLICY ticket_assets_select ON public.ticket_assets FOR SELECT TO authenticated USING ((EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_assets.ticket_id AND ((t.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))))) OR EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_assets.ticket_id AND (t.user_id = (SELECT auth.uid()) OR t.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)))));
CREATE POLICY ticket_assets_insert ON public.ticket_assets FOR INSERT TO authenticated WITH CHECK (EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_assets.ticket_id AND ((t.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)))));
CREATE POLICY ticket_assets_update ON public.ticket_assets FOR UPDATE TO authenticated USING (EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_assets.ticket_id AND ((t.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role))))) WITH CHECK (EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_assets.ticket_id AND ((t.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)))));
CREATE POLICY ticket_assets_delete ON public.ticket_assets FOR DELETE TO authenticated USING (EXISTS (SELECT 1 FROM public.tickets t WHERE t.id = ticket_assets.ticket_id AND ((t.company_id = (SELECT public.get_user_company_id((SELECT auth.uid()))) AND ((SELECT public.has_role((SELECT auth.uid()), 'admin'::public.app_role)) OR (SELECT public.has_role((SELECT auth.uid()), 'technician'::public.app_role)))) OR (SELECT public.is_master_company_user((SELECT auth.uid()))) OR (SELECT public.has_role((SELECT auth.uid()), 'developer'::public.app_role)))));

